package com.effectivejava.C_ClassesAndInterfaces.LimitSourceFilesToASingleTopLevelClass;

// Two classes defined in one file. Don't ever do this!
public class Utensil {
    public static final String NAME="pan";

}
//eğer bu sınıf başka bir sınıf içinde tekrar tanımlanırsa compiler o sınıfı derlemez.
class Dessert {
    public static final String NAME="cake";
}

/**
 * The lesson is clear: Never put multiple top-level classes or interfaces in a
 * single source file. Following this rule guarantees that you can’t have multiple
 * definitions for a single class at compile time. This in turn guarantees that the class
 * files generated by compilation, and the behavior of the resulting program, are
 * independent of the order in which the source files are passed to the compiler.
 */
